name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy code to VPS
        run: |
          rsync -avz --delete ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/root/app/
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no"

      - name: SSH and deploy
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            set -e
            cd /root/app

            # Substitui placeholders de domínio e e-mail
            sed -i "s/2fsolucoes.com.br/${DOMAIN}/g" docker-compose.prod.yml
            sed -i "s/felipecacezi@gmail.com/${EMAIL}/g" docker-compose.prod.yml

            # Limpa imagens antigas (opcional)
            docker image prune -af

            # Build da imagem local usando Dockerfile.prod
            docker build -t frontend:latest -f ./frontend/Dockerfile.prod ./frontend

            # Deploy no Swarm usando a imagem local
            docker stack deploy -c docker-compose.prod.yml myapp
          EOF
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
